In [1]:
import os
from dotenv import load_dotenv
from FinMind.data import DataLoader
import pandas as pd

In [ ]:
df = pd.read_parquet("../data/brokers/1470/2024-01-01_to_2026-01-01.parquet")
# df[df["stock_id"] == "0050"]
unique_values = set(df["date"].unique())

In [34]:
df[df["stock_id"] == "0050"]

,date,stock_id,securities_trader,securities_trader_id,buy_amount,sell_amount,buy,sell,net_buy,net_buy_amount,avg_price
6452,2024-01-10,0050,台灣摩根,1470,7948300.0,0.0,60000,0,60000,7948300.0,132.471667
9434,2024-01-15,0050,台灣摩根,1470,31592100.0,0.0,237000,0,237000,31592100.0,133.300000
12007,2024-01-17,0050,台灣摩根,1470,0.0,37711350.0,0,295000,-295000,-37711350.0,127.835085
15197,2024-01-22,0050,台灣摩根,1470,34356750.0,0.0,257000,0,257000,34356750.0,133.683852
18059,2024-01-25,0050,台灣摩根,1470,38102000.0,0.0,282000,0,282000,38102000.0,135.113475
...,...,...,...,...,...,...,...,...,...,...,...
542764,2025-12-19,0050,台灣摩根,1470,0.0,29855650.0,0,477000,-477000,-29855650.0,62.590461
543937,2025-12-22,0050,台灣摩根,1470,0.0,506926300.0,0,8011000,-8011000,-506926300.0,63.278779
548816,2025-12-29,0050,台灣摩根,1470,65050.0,0.0,1000,0,1000,65050.0,65.050000
550042,2025-12-30,0050,台灣摩根,1470,0.0,64900.0,0,1000,-1000,-64900.0,64.900000
551239,2025-12-31,0050,台灣摩根,1470,5904000.0,0.0,90000,0,90000,5904000.0,65.600000

In [23]:
df

,date,stock_id,securities_trader,securities_trader_id,buy_amount,sell_amount,buy,sell,net_buy,net_buy_amount,avg_price
0,2021-06-30,0056,美林,1440,12913390.0,34860.0,369000,1000,368000,12878530.0,34.996005
1,2021-06-30,00683L,美林,1440,0.0,34200.0,0,2000,-2000,-34200.0,17.100000
2,2021-06-30,00708L,美林,1440,50920.0,151980.0,2000,6000,-4000,-101060.0,25.265000
3,2021-06-30,1101,美林,1440,12919500.0,40151400.0,253000,787000,-534000,-27231900.0,50.996067
4,2021-06-30,1102,美林,1440,5485100.0,3613900.0,108000,71000,37000,1871200.0,50.572973
...,...,...,...,...,...,...,...,...,...,...,...
1458035,2026-02-11,9945,美林,1440,6605601.2,11217700.0,226536,385000,-158464,-4612098.8,29.105026
1458036,2026-02-11,9946,美林,1440,529600.0,0.0,32000,0,32000,529600.0,16.550000
1458037,2026-02-11,9955,美林,1440,788150.0,97950.0,24000,3000,21000,690200.0,32.866667
1458038,2026-02-11,9958,美林,1440,18784500.0,376000.0,150000,3000,147000,18408500.0,125.227891
1458039,2026-02-11,9960,美林證券,1440,23000.0,0.0,1000,0,1000,23000.0,23.000000

In [ ]:
class BrokerTradeTracker:

    def __init__(self, securities_trader: str, securities_trader_id: str, stock_id: str) -> None:
        self.securities_trader: str = securities_trader
        self.securities_trader_id: str = securities_trader_id
        self.stock_id = stock_id

    def add_record(self, df: pd.DataFrame) -> None:
        self.date = df["date"]